INSERT INTO estado (nombre,fecha_creacion) VALUES ('prueba','2022-03-01');
INSERT INTO estado (nombre,fecha_creacion) VALUES ('prueba2','2022-03-02');
INSERT INTO estado (nombre,fecha_creacion) VALUES ('prueba3','2022-03-03');
INSERT INTO estado (nombre,fecha_creacion) VALUES ('prueba4','2022-03-03');
INSERT INTO tipo_objeto (activo, fecha_creacion) VALUES(true,'2022-03-29');
INSERT INTO tipo_objeto (activo, fecha_creacion) VALUES(true,'2022-03-30');
INSERT INTO tipo_objeto (activo, fecha_creacion) VALUES(true,'2022-03-31');
INSERT INTO tipo_objeto (activo, fecha_creacion) VALUES(true,'2022-03-31');
INSERT INTO objeto_estado (id_estado, id_objeto, fecha_alcanzado,observaciones) VALUES(2,1,'2022-05-08','estamos en IT');
INSERT INTO objeto_estado (id_estado, id_objeto, fecha_alcanzado,observaciones) VALUES(3,2,'2022-05-09','estamos en IT');
INSERT INTO objeto_estado (id_estado, id_objeto, fecha_alcanzado,observaciones) VALUES(4,3,'2022-05-10','estamos en IT');
INSERT INTO objeto (nombre, observaciones) VALUES ('agregado en IT','es de .sql');
INSERT INTO objeto (nombre, observaciones) VALUES ('agregado en IT','es de .sql');
INSERT INTO objeto (nombre, observaciones) VALUES ('agregado en IT','es de .sql');
INSERT INTO objeto (nombre, observaciones) VALUES ('agregado en IT 2','es de .sql');
INSERT INTO objeto (nombre, observaciones) VALUES ('agregado','es de .sql');